# Generated by Django 2.0 on 2018-08-19 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('url', models.URLField(default='https://amzn.to/2vRFY1m')),
                ('button_url', models.URLField(default='\n\t\t\thttp://g-ec2.images-amazon.com/images/G/31/img14/anywhere/amazon-logo-500500._V327001990_.jpg\n\t\t')),
                ('detail1', models.CharField(blank=True, default='', max_length=300)),
                ('detail2', models.CharField(blank=True, default='', max_length=300)),
                ('detail3', models.CharField(blank=True, default='', max_length=300)),
                ('vote', models.IntegerField(default=0)),
                ('cost', models.CharField(blank=True, max_length=1000000000000)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('end', models.DateTimeField()),
                ('published', models.CharField(default='0', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotingApp.Emails')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotingApp.Titles')),
            ],
        ),
        migrations.AddField(
            model_name='options',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotingApp.Titles'),
        ),
    ]
