# Generated by Django 2.0 on 2018-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='emailed',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='titles',
            name='published',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
