# Generated by Django 2.0 on 2018-10-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0002_auto_20180826_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
